# Generated by Django 5.2.4 on 2026-04-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditoría',
                'db_table': '',
                'permissions': [('ver_auditoria', 'Puede ver la auditoría del sistema')],
                'managed': False,
            },
        ),
    ]
