# Generated by Django 5.2.4 on 2025-08-12 20:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0002_categoria_remove_producto_tipo_producto_precio_venta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150, verbose_name='Nombre y apellido')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=16)),
                ('mail', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=50)),
                ('nro_afiliado', models.CharField(max_length=50, verbose_name='Número de Afiliado')),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='dirección')),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Graduacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('od_lejos_esferico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OD Lejos Esférico')),
                ('od_lejos_cilindrico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OD Lejos Cilíndrico')),
                ('od_lejos_eje', models.PositiveIntegerField(blank=True, null=True, verbose_name='OD Lejos Eje')),
                ('oi_lejos_esferico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OI Lejos Esférico')),
                ('oi_lejos_cilindrico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OI Lejos Cilíndrico')),
                ('oi_lejos_eje', models.PositiveIntegerField(blank=True, null=True, verbose_name='OI Lejos Eje')),
                ('od_cerca_esferico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OD Cerca Esférico')),
                ('od_cerca_cilindrico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OD Cerca Cilíndrico')),
                ('od_cerca_eje', models.PositiveIntegerField(blank=True, null=True, verbose_name='OD Cerca Eje')),
                ('oi_cerca_esferico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OI Cerca Esférico')),
                ('oi_cerca_cilindrico', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='OI Cerca Cilíndrico')),
                ('oi_cerca_eje', models.PositiveIntegerField(blank=True, null=True, verbose_name='OI Cerca Eje')),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduacion', to='ventas.consulta')),
            ],
            options={
                'verbose_name_plural': 'Graduaciones',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='obra_social',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.obrasocial'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('forma_pago', models.CharField(choices=[('CO', 'Contado'), ('DE', 'Tarjeta de Debito'), ('CR', 'Tarjeta de Credito'), ('TR', 'Transferencia'), ('QR', 'QR')], default='CO', max_length=2, verbose_name='Forma de pago')),
                ('entrego', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='entregó')),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('subtotal_item', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ventas', to='ventas.venta')),
            ],
        ),
    ]
