# Generated by Django 5.2.4 on 2025-09-27 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_alter_venta_saldo_alter_venta_total_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduacion',
            name='od_cerca_eje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='OD Cerca Eje'),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='od_lejos_eje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='OD Lejos Eje'),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_cerca_eje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='OI Cerca Eje'),
        ),
        migrations.AlterField(
            model_name='graduacion',
            name='oi_lejos_eje',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(180)], verbose_name='OI Lejos Eje'),
        ),
    ]
