# Generated by Django 5.2.4 on 2025-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_alter_graduacion_od_cerca_eje_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='porcentaje_ganancia',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta para este producto (editable)', max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
