# Generated by Django 5.2.4 on 2025-10-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_cliente_direccion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente/Paciente', 'verbose_name_plural': 'Clientes/Pacientes'},
        ),
    ]
