# Generated by Django 5.2.4 on 2026-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0008_historicalcliente_historicalconsulta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalconsulta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalconsulta',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleventa',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleventa',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='historicalgraduacion',
            name='consulta',
        ),
        migrations.RemoveField(
            model_name='historicalgraduacion',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalobrasocial',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalventa',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalventa',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCliente',
        ),
        migrations.DeleteModel(
            name='HistoricalConsulta',
        ),
        migrations.DeleteModel(
            name='HistoricalDetalleVenta',
        ),
        migrations.DeleteModel(
            name='HistoricalGraduacion',
        ),
        migrations.DeleteModel(
            name='HistoricalObraSocial',
        ),
        migrations.DeleteModel(
            name='HistoricalVenta',
        ),
    ]
