web: exec gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --log-level debug --access-logfile - --error-logfile -
release: python manage.py migrate --no-input && python manage.py collectstatic --no-input
