[build]
buildCommand = "apt-get update && apt-get install -y build-essential pkg-config libcairo2 libcairo2-dev libpango1.0-0 libpango1.0-dev libglib2.0-0 libglib2.0-dev libffi-dev && python -m pip install -r ./requirements.txt"

[deploy]
startCommand = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2"
restartPolicyType = "on_failure"
