# Generated by Django 5.2.4 on 2025-10-06 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ventas', '0006_alter_cliente_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100, unique=True)),
                ('hora_apertura', models.TimeField(default='09:00', help_text='Hora de apertura')),
                ('hora_cierre', models.TimeField(default='18:00', help_text='Hora de cierre')),
                ('duracion_turno_default', models.PositiveIntegerField(default=30, help_text='Duración por defecto de los turnos en minutos')),
                ('activa', models.BooleanField(default=True, help_text='Indica si esta configuración está activa')),
            ],
            options={
                'verbose_name': 'Configuración de Calendario',
                'verbose_name_plural': 'Configuraciones de Calendario',
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha del turno')),
                ('hora_inicio', models.TimeField(help_text='Hora de inicio del turno')),
                ('hora_fin', models.TimeField(blank=True, help_text='Hora de finalización (se calcula automáticamente)', null=True)),
                ('motivo', models.TextField(blank=True, help_text='Motivo específico de la consulta', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones internas del personal', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(help_text='Cliente al que se asigna el turno', on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='ventas.cliente')),
                ('created_by', models.ForeignKey(blank=True, help_text='Usuario que creó el turno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['fecha', 'hora_inicio'], name='turnos_turn_fecha_9c2808_idx'), models.Index(fields=['cliente', 'fecha'], name='turnos_turn_cliente_72ba5b_idx')],
            },
        ),
    ]
