# Generated by Django 5.2.4 on 2026-03-16 15:22

import turnos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracioncalendario',
            name='dias_laborables',
            field=models.JSONField(default=turnos.models._default_dias_laborables, help_text='Días laborables (0=Dom, 1=Lun, 2=Mar, 3=Mié, 4=Jue, 5=Vie, 6=Sáb)'),
        ),
    ]
