# Generated by Django 5.2.4 on 2026-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0003_historicalturno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalTurno',
        ),
    ]
