# Generated by Django 5.2.4 on 2025-10-14 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
    ]
