# Generated by Django 5.2.4 on 2025-10-14 20:29

from django.db import migrations, models


def migrate_data_forward(apps, schema_editor):
    """Migración manual para MySQL que verifica si las columnas existen."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar y eliminar índice si existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND index_name = 'contabilida_tipo_e91636_idx'
        """
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja DROP INDEX contabilida_tipo_e91636_idx"
            )

        # Agregar columnas ingreso y egreso si no existen
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name = 'ingreso'
        """
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja ADD COLUMN ingreso DECIMAL(10, 2) NOT NULL DEFAULT 0"
            )

        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name = 'egreso'
        """
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja ADD COLUMN egreso DECIMAL(10, 2) NOT NULL DEFAULT 0"
            )

        # Migrar datos si existen las columnas tipo y monto
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name IN ('tipo', 'monto')
        """
        )
        if cursor.fetchone()[0] == 2:
            # Migrar datos existentes
            cursor.execute(
                """
                UPDATE contabilidad_movimientocaja
                SET ingreso = CASE WHEN tipo = 'INGRESO' THEN monto ELSE 0 END,
                    egreso = CASE WHEN tipo = 'EGRESO' THEN monto ELSE 0 END
            """
            )

            # Eliminar columnas antiguas
            cursor.execute("ALTER TABLE contabilidad_movimientocaja DROP COLUMN tipo")
            cursor.execute("ALTER TABLE contabilidad_movimientocaja DROP COLUMN monto")


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0002_add_movimiento_caja"),
    ]

    operations = [
        migrations.RunPython(
            migrate_data_forward, reverse_code=migrations.RunPython.noop
        ),
    ]
