# Generated by Django 5.2.4 on 2025-10-14 20:39

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Elimina el índice solo si existe (para evitar errores en producción)."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar si el índice existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND index_name = 'contabilida_tipo_e91636_idx'
        """
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja DROP INDEX contabilida_tipo_e91636_idx"
            )


def remove_fields_if_exist(apps, schema_editor):
    """Elimina campos solo si existen (para evitar errores en producción)."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Lista de campos a eliminar
        fields_to_remove = ["concepto", "monto", "tipo"]

        for field in fields_to_remove:
            # Verificar si el campo existe
            cursor.execute(
                f"""
                SELECT COUNT(*)
                FROM information_schema.columns
                WHERE table_schema = DATABASE()
                AND table_name = 'contabilidad_movimientocaja'
                AND column_name = '{field}'
            """
            )
            if cursor.fetchone()[0] > 0:
                cursor.execute(
                    f"ALTER TABLE contabilidad_movimientocaja DROP COLUMN {field}"
                )


def add_fields_if_not_exist(apps, schema_editor):
    """Agrega campos solo si no existen (para evitar errores en producción)."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar y agregar campo 'egreso'
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name = 'egreso'
        """
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja ADD COLUMN egreso DECIMAL(10, 2) NOT NULL DEFAULT 0"
            )

        # Verificar y agregar campo 'ingreso'
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name = 'ingreso'
        """
        )
        if cursor.fetchone()[0] == 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja ADD COLUMN ingreso DECIMAL(10, 2) NOT NULL DEFAULT 0"
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "contabilidad",
            "0003_remove_movimientocaja_contabilida_tipo_e91636_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            remove_fields_if_exist,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            add_fields_if_not_exist,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
