# Generated by Django 5.2.4 on 2025-10-14 20:39

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Elimina el índice solo si existe (para evitar errores en producción)."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar si el índice existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND index_name = 'contabilida_tipo_e91636_idx'
        """
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja DROP INDEX contabilida_tipo_e91636_idx"
            )


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_remove_movimientocaja_contabilida_tipo_e91636_idx_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='egreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egreso'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso'),
        ),
    ]
