# Generated by Django 5.2.4 on 2025-10-14 20:39

from django.db import migrations


def remove_concepto_field(apps, schema_editor):
    """Elimina el campo concepto si existe en MySQL."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar si la columna concepto existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND column_name = 'concepto'
        """
        )
        if cursor.fetchone()[0] > 0:
            cursor.execute(
                "ALTER TABLE contabilidad_movimientocaja DROP COLUMN concepto"
            )


class Migration(migrations.Migration):

    dependencies = [
        (
            "contabilidad",
            "0004_remove_movimientocaja_contabilida_tipo_e91636_idx_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            remove_concepto_field, reverse_code=migrations.RunPython.noop
        ),
    ]
