# Generated by Django 5.2.4 on 2025-10-14 20:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_remove_concepto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movimientocaja',
            constraint=models.UniqueConstraint(fields=('fecha',), name='unique_movimiento_por_dia'),
        ),
    ]
