# Generated by Django 5.2.4 on 2025-10-14 20:46

from django.db import migrations


def add_unique_constraint(apps, schema_editor):
    """Agrega la restricción única para fecha si no existe."""
    if schema_editor.connection.vendor != "mysql":
        return

    with schema_editor.connection.cursor() as cursor:
        # Verificar si la restricción ya existe
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.table_constraints
            WHERE table_schema = DATABASE()
            AND table_name = 'contabilidad_movimientocaja'
            AND constraint_name = 'unique_movimiento_por_dia'
        """
        )

        if cursor.fetchone()[0] == 0:
            # Primero, eliminar duplicados si existen
            cursor.execute(
                """
                DELETE t1 FROM contabilidad_movimientocaja t1
                INNER JOIN contabilidad_movimientocaja t2
                WHERE t1.id > t2.id AND t1.fecha = t2.fecha
            """
            )

            # Agregar la restricción
            cursor.execute(
                """
                ALTER TABLE contabilidad_movimientocaja
                ADD CONSTRAINT unique_movimiento_por_dia UNIQUE (fecha)
            """
            )


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad", "0006_movimientocaja_unique_movimiento_por_dia"),
    ]

    operations = [
        migrations.RunPython(
            add_unique_constraint, reverse_code=migrations.RunPython.noop
        ),
    ]
