# Generated by Django 5.2.4 on 2025-10-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_add_unique_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocaja',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Inicial'),
        ),
    ]
