# Generated by Django 5.2.4 on 2025-10-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_movimientocaja_saldo_inicial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientocaja',
            name='saldo_inicial',
        ),
    ]
