# Generated by Django 5.2.4 on 2026-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_remove_movimientocaja_saldo_inicial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movimientocaja',
            name='contabilida_tipo_e91636_idx',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='concepto',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='movimientocaja',
            name='tipo',
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='egreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Egreso'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='ingreso',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ingreso'),
        ),
    ]
