# Generated by Django 5.2.4 on 2026-02-10 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_remove_movimientocaja_saldo_inicial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovimientoCaja',
        ),
    ]
