# Generated by Django 5.2.4 on 2026-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_remove_movimientocaja_saldo_inicial'),
    ]

    operations = [
        # Esta migración se vacía porque el modelo MovimientoCaja
        # es eliminado en 0010_delete_movimientocaja (branch paralelo)
        # Mantener las operaciones causaría KeyError en el merge
    ]
