# Generated by Django 5.2.4 on 2026-02-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0010_delete_movimientocaja'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Reporte de Caja',
                'verbose_name_plural': 'Contabilidad',
                'permissions': [('ver_reporte_caja', 'Puede ver el reporte de caja')],
                'managed': False,
            },
        ),
    ]
