# Generated by Django 5.2.4 on 2026-02-10 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportecaja',
            options={'managed': False, 'permissions': [('ver_reporte_caja', 'Puede ver el reporte de caja')], 'verbose_name': 'Reporte de Caja', 'verbose_name_plural': 'Reporte de Caja'},
        ),
    ]
