# Generated by Django 5.2.4 on 2026-02-10 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0012_alter_reportecaja_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reportecaja',
            table='',
        ),
    ]
