# Generated by Django 5.2.4 on 2026-02-23 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_remove_movimientocaja_contabilida_tipo_e91636_idx_and_more'),
        ('contabilidad', '0013_alter_reportecaja_table'),
    ]

    operations = [
    ]
