# Generated by Django 5.2.4 on 2025-08-01 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('AR', 'Armazon'), ('LE', 'Lentes'), ('MA', 'Marcos'), ('CR', 'Cristal')], max_length=2)),
                ('descripcion', models.TextField()),
                ('stock', models.PositiveIntegerField()),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de costo')),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.marca')),
            ],
        ),
    ]
