# Generated by Django 5.2.4 on 2025-08-12 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria_remove_producto_tipo_producto_precio_venta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Precio de venta'),
        ),
    ]
