# Generated by Django 5.2.4 on 2025-09-30 13:21

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_alter_producto_marca'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimoCambioPrecio',
            fields=[
                ('producto', models.OneToOneField(help_text='Producto al que pertenece este registro de cambio', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ultimo_cambio_precio', serialize=False, to='productos.producto')),
                ('precio_anterior', models.DecimalField(decimal_places=2, help_text='Precio de costo anterior al último cambio', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio antes del último cambio')),
                ('precio_actual', models.DecimalField(decimal_places=2, help_text='Precio de costo actual después del último cambio', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio después del último cambio')),
                ('tipo_ultimo_cambio', models.CharField(choices=[('aumento_lote', 'Aumento en lote'), ('manual', 'Cambio manual'), ('reversion', 'Reversión')], default='manual', max_length=15, verbose_name='Tipo de cambio')),
                ('porcentaje_aplicado', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje aplicado en el último aumento (solo para aumentos en lote)', max_digits=5, null=True, verbose_name='Porcentaje del último aumento')),
                ('lote_id', models.CharField(blank=True, db_index=True, help_text='Identificador del lote si fue un cambio en lote', max_length=50, null=True, verbose_name='ID del último lote')),
                ('fecha_ultimo_cambio', models.DateTimeField(auto_now=True, help_text='Fecha y hora del último cambio de precio', verbose_name='Fecha del último cambio')),
                ('usuario_ultimo_cambio', models.CharField(help_text='Usuario que realizó el último cambio de precio', max_length=150, verbose_name='Usuario que realizó el cambio')),
            ],
            options={
                'verbose_name': 'Último Cambio de Precio',
                'verbose_name_plural': 'Últimos Cambios de Precios',
                'db_table': 'productos_ultimo_cambio_precio',
                'indexes': [models.Index(fields=['lote_id'], name='idx_lote_id'), models.Index(fields=['tipo_ultimo_cambio'], name='idx_tipo_cambio'), models.Index(fields=['fecha_ultimo_cambio'], name='idx_fecha_cambio')],
            },
        ),
    ]
