# Generated by Django 5.2.4 on 2026-01-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_ultimocambioprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='porcentaje_ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de ganancia sobre el precio de costo (ej: 30.00 para 30%)', max_digits=5, null=True, verbose_name='Porcentaje de ganancia'),
        ),
    ]
