# Generated by Django 5.2.4 on 2026-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_historicalcategoria_historicalmarca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmarca',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproducto',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalsubcategoria',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCategoria',
        ),
        migrations.DeleteModel(
            name='HistoricalMarca',
        ),
        migrations.DeleteModel(
            name='HistoricalProducto',
        ),
        migrations.DeleteModel(
            name='HistoricalSubCategoria',
        ),
    ]
