# Generated by Django 5.2.4 on 2025-09-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_gasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario'),
        ),
    ]
