# Generated by Django 5.2.4 on 2025-09-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detallecompra_precio_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta sugerido para este producto', max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
