# Generated by Django 5.2.4 on 2026-03-24 15:27

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_compra_proveedor_not_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Porcentaje de ganancia sobre el precio unitario (ej: 30.00 para 30%)', max_digits=5, verbose_name='Porcentaje de ganancia'),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Calculado automáticamente: precio_unitario × (1 + porcentaje_ganancia / 100)', max_digits=10, verbose_name='Precio de venta'),
        ),
    ]
