# Generated by Django 5.2.4 on 2026-03-25 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_add_porcentaje_ganancia_to_detallecompra'),
        ('productos', '0007_producto_porcentaje_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCostoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_costo', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de costo')),
                ('fecha', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_costos', to='productos.producto')),
            ],
            options={
                'verbose_name': 'Historial de Costo',
                'verbose_name_plural': 'Historial de Costos',
                'ordering': ['-fecha', '-id'],
            },
        ),
    ]
