# Generated by Django 5.2.4 on 2026-03-25 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_add_historialcostoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcostoproducto',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.compra'),
        ),
    ]
