# Generated by Django 5.2.4 on 2026-03-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0008_add_compra_fk_to_historialcosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcostoproducto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio real de compra'),
        ),
        migrations.AlterField(
            model_name='historialcostoproducto',
            name='precio_costo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio promedio'),
        ),
    ]
