# Generated by Django 5.2.4 on 2026-04-16 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0010_historicalcompra_historicaldetallecompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldetallecompra',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='historicaldetallecompra',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetallecompra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='historicalgasto',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproveedor',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalCompra',
        ),
        migrations.DeleteModel(
            name='HistoricalDetalleCompra',
        ),
        migrations.DeleteModel(
            name='HistoricalGasto',
        ),
        migrations.DeleteModel(
            name='HistoricalProveedor',
        ),
    ]
