# Generated by Django 5.2.4 on 2026-04-16 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la operación.')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar')], help_text='Tipo de operación realizada.', max_length=10)),
                ('modelo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('producto', 'Producto'), ('turno', 'Turno')], help_text='Modelo sobre el que se realizó la operación.', max_length=20)),
                ('objeto_id', models.IntegerField(help_text='ID del objeto afectado.')),
                ('detalle', models.JSONField(help_text='Snapshot o diff completo de la operación.')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó la operación.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='auditoria_r_modelo_e0db67_idx'), models.Index(fields=['fecha'], name='auditoria_r_fecha_ee69fc_idx'), models.Index(fields=['usuario'], name='auditoria_r_usuario_5ab20b_idx')],
            },
        ),
    ]
